name: PUSH TESTE PULL
on:
  push:
    branches:
      - teste-pull
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: "postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@db_students_postgres:5432/${{secrets.POSTGRES_DB}}"
          file_name: .env.test
      - name: Deploy Prisma to migrations
        run: npm run prisma:deploy
      - name: Build
        run: npm i && npm run build
          # fail_on_empty: true
      # - name: Build process docker-compose
        # run: docker-compose build
      # - name: Run app docker compose
      #   run: docker-compose down && docker-compose up -d